language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
addons:
  apt:
    packages:
      - google-chrome-beta
env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
